"""兼容层：Win32 原语已搬到 `aurora.platform.winapi`（P3.6），这里保留同名转发。"""
from __future__ import annotations

from aurora.platform.winapi import (  # noqa: F401  (re-export)
    DWMWA_USE_IMMERSIVE_DARK_MODE,
    DWMWA_WINDOW_CORNER_PREFERENCE,
    DWMWA_BORDER_COLOR,
    DWMWCP_ROUND,
    DWMWCP_ROUNDSMALL,
    SWP_NOSIZE,
    SWP_NOMOVE,
    SWP_NOZORDER,
    SWP_NOACTIVATE,
    SWP_FRAMECHANGED,
    SW_MAXIMIZE,
    SW_RESTORE,
    SW_SHOW,
    ASFW_ANY,
    _user32,
    _dwmapi,
    _set_dwm,
    handle_of,
    find_window,
    focus_window,
    raise_window,
    _attach_thread_input,
    BORDER_DARK,
    BORDER_LIGHT,
    system_prefers_light,
    set_dark_frame,
    polish,
    _as_ico,
    set_icon,
    maximize,
    restore,
    is_maximized,
    toggle_maximize,
    get_rect,
    set_rect,
    dpi_scale,
)
